#!/bin/sh -xeu
scriptdir="$(dirname -- "$(realpath -- "$0")")"

if ! [ -f "$scriptdir/target/release/element-desktop-export" ]; then
	(
		cd -- "$scriptdir"
		cargo build --release
	)
fi

PATH="$PATH:$scriptdir"

if ! command -v deno; then
	(
		cd -- "$scriptdir"
		curl -L https://github.com/denoland/deno/releases/ | grep -Eiom1 '/[^"]*/[^"]+-(amd64|x86_64)-unknown-linux-gnu.zip' | xargs -tI{} curl -L https://github.com/{} | jar x deno
		chmod +x deno
	)
fi

mkdir -p logs
"$scriptdir/target/release/element-desktop-export" "$@" | "$scriptdir/main.js"
